### ISSUE TITLE
Validation des défis impossible, le reload est trop rapide

### ISSUE THREAD

**Issue by tlegoc** [BDE-ISATI/wei_app_v2#16]

**Comment by Caeles12** [comment]
Faut modifier le navigate(0) qui reload la page pour juste supprimer dans la liste affichée la demande de validation quand on reçoit un 200 OK. Comme ça pas d'appel API inutile en trop (j'avais mis le reload par flemme mdr)

**Comment by tlegoc** [comment]
Bug confondu avec le bug 5 sur wei_app_api_v2
